DROP TABLE IF EXISTS NEWS;
CREATE TABLE NEWS(
        id LONG  NOT NULL AUTO_INCREMENT PRIMARY KEY,
        title text not null,
        body text not null,
        date datetime  not null default (current_time),
        type varchar default 'none'
);

insert into NEWS(title, body,type) values ( 'Morgan keeps England cards close to his chest for New Zealand reshuffle', '<p>Like the main characters in Four Weddings and a Funeral, the cricket teams of England and New Zealand don’t seem to be able to go to a party without running into each other. There have been five meetings at major international tournaments since the start of 2015, and so far as England are concerned four have been raucous celebrations, and one very much a wake. </p>
                                            <p>England’s humiliating thrashing in Wellington at the 2015 ODI World Cup was instrumental in propelling them towards their current state of white-ball excellence, with both of the sides that will meet in Abu Dhabi on Wednesday impacted in different ways by the team led then by Brendon McCullum. Since then their stars have seemed aligned, and now they are set for yet another sequel.</p>
                                            <p>It is a match that became massively harder to predict in a single instant on Saturday night when Jason Roy set off for a single and his calf muscle refused to cooperate. While England will be particularly pained by the absence of their opener – a man Eoin Morgan said “epitomises everything that we are about in the changing room and the way that we play” – in many ways this is a match between two teams both suffering, in very different ways, from the same injury.</p>
                                            <p>The impact on England is obvious, and it has forced them to approach their most important game of the tournament so far with an unwanted reorganisation. But that too impacts on New Zealand, whose tactical planning has been thrown into disarray. Had Roy been fit England would almost certainly have been unchanged for this game and New Zealand’s task would be more daunting but also more predictable. In his absence New Zealand have at the centre of their preparations a lot of guesswork and crossed fingers.</p>','sport' ),
                                          ('Emma Raducanu’s season ends with painful Linz defeat to Wang Xinyu','<p>Emma Raducanu arrived in Linz with the simple goal of gaining more experience and matchplay in her final week of an unimaginably intense year, but she was unable to avoid that enormous, growing target on her back.</p> ' ||
                                                                                                                '<p>Starting, illogically, as the top seed in just her seventh WTA event, Raducanu fought until the end but succumbed to a tough opponent and injury in the final games, losing 6-1, 6-7 (0), 7-5 to Wang Xinyu of China in the second round of the Upper Austria Ladies Linz.<p>' ||
                                                                                                                '<p>As in the Transylvania Open, when she lost heavily to her fellow teenager Marta Kostyuk, Raducanu was facing a contemporary who enjoyed a more spectacular junior career. Before their meeting, Wang cited Raducanu’s US Open win as an inspiration for young players and for all Chinese players due to Raducanu’s heritage.</p>','sport'),
                                          ('Stocks making the biggest moves after hours: Coinbase, Poshmark, DoorDash and more','<p>Coinbase — Shares of Coinbase dropped more than 13% after the company reported quarterly revenue of $1.31 billion, which missed analysts’ expectations. Monthly active transaction users were lower from the previous quarter, at 7.4 million, but up from the prior year. Transaction-based revenue was also lower from the previous quarter.</p>' ||
                                                                                                                                '<p>Poshmark — The social marketplace’s shares tumbled about 27% after it reported quarterly results. It reported a loss of 9 cents per share, versus analyst estimates of 7 cents per share. Revenue also came in weaker than expected at $79.7 million, versus $82.7 million expected by Wall Street.</p>' ||
                                                                                                                                '<p>Aurora — The cannabis company’s shares fell 3.7% in extended trading after the company reported a slight revenue miss in its quarterly results. Aurora recorded CAD $60.1 million compared to estimates of CAD $60.6 million. It also reported a 23% increase in sales of medical cannabis, however, sales of recreational cannabis declined 44%. Recreational cannabis makes up 95% of sales across Canada.</p>' ||
                                                                                                                                '<p>DoorDash — The food delivery platform saw its shares jump 5% after announcing its biggest acquisition to date of Wolt, the Finland-based delivery app, for 7 billion euros, or about $8.1 billion. The company also reported its quarterly results, which included a wider than expected loss of 30 cents per share versus 26 cents pre share.</p>' ||
                                                                                                                                '<p>FuboTV — Shares of the sports live television streaming platform fell 4% after it reported a loss of 47 cents per share and revenue of $156.7 million for the third quarter. The company also increased its guidance for the fourth quarter.</p>','finance'),
                                          ('Thousands of Americans living abroad got stimulus checks. Here’s why','<p>Thousands of Americans living abroad received stimulus checks during the Covid-19 pandemic, according to federal data.</p>' ||
                                                                                                                  '<p>While that may sound incongruous with the notion of “stimulus” for the U.S. economy, lawmakers generally had a sound rationale for sending funds overseas, according to tax policy experts.</p>' ||
                                                                                                                  '<p>“They are casting a very broad net and [payments may] go to places where people think, ‘Did they really need to go there?’” said Kyle Pomerleau, a senior fellow at the American Enterprise Institute, a right-leaning think tank. “But I think the answer is generally, ‘Yes.’”</p>' ||
                                                                                                                  '<p>The IRS issued more than 3.7 million payments worth $5.5 billion to individuals outside the 50 states and Washington, D.C., according to agency statistics. The figures include three rounds of pandemic-era payments through June 3, 2021. (Additional payments may have been sent since then.)</p>' ||
                                                                                                                  '<p>The data encompasses U.S. citizens abroad, military members stationed overseas and residents of U.S. territories such as Puerto Rico. (While U.S. territories aren’t “overseas” in the sense that foreign countries are, the IRS doesn’t report these statistics separately.)</p>','finance'),
                                          ('Ousted WeWork CEO says $47 billion valuation went to his head before botched IPO','<p>Ousted WeWork CEO Adam Neumann said Tuesday that the company’s private, $47 billion valuation went to his head, in the first interview since departing the company in 2019 amid its botched IPO.</p>' ||
                                                                                                                              '<p>“So yes the valuation made us feel like we were right, which made me feel that whatever style I was leading at was a correct style at the time, so I do think it affected it,” he told CNBC’s Andrew Ross Sorkin at The New York Times DealBook online summit. “I also think the chase ... maybe it went to my head. I do think at some point it did.”</p>' ||
                                                                                                                              '<p>The interview comes less than a month after the company went public through a SPAC merger with a $9 billion valuation.</p>' ||
                                                                                                                              '<p>Neumann confirmed reports that JPMorgan Chase CEO Jamie Dimon, the bank tapped with leading the IPO, convinced him to step down from the company. He also talked about lessons learned, addressing the backlash surrounding the roughly $1 billion he got when he walked away from WeWork.</p>' ||
                                                                                                                              '<p>“This perception that as the company went from a $47 billion valuation down to $9 billion, that I profited somehow while the company was going down, is completely false,” he said, adding that it was a narrative he couldn’t correct because he “wasn’t speaking.”</p>' ||
                                                                                                                              '<p>Neumann said he understands the perception and is “disappointed” for the employees that lost their jobs or took lower salaries and stock because they believed in the company. He said he never intended for the company not to succeed, but every start-up has risks.</p>' ||
                                                                                                                              '<p>“When you take equity ... and you join a start-up, you take a risk,” he said. “Now, I wish it would have worked out differently for everybody but the market now decided that it’s worth $9 billion. It’s getting measured on a daily basis and I actually think WeWork today has a better opportunity than it had then.”</p>' ||
                                                                                                                              '<p>Neumann also responded to allegations of drinking and drug use at the company. He said they “make good stories for movies and television shows.” He added that weed is the only drug he’s aware of and that WeWork had a “fun” culture.</p>' ||
                                                                                                                              '<p>He did not comment on a suggestion from the audience to share his wealth with WeWork employees but said he and co-founder Miguel McKelvey have done things privately with their money that they are not ready to discuss. Neumann added that he is currently investing through a family office, and he’s interested in cryptocurrencies.</p>','finance'),
                                          ('Myanmar is planning to reopen to tourism in early 2022. But who will go?','<p>(CNN) — As multiple Southeast Asia countries begin to ease travel restrictions, Myanmar, which boasts some of the region''s most spectacular destinations, has announced that it hopes to begin welcoming international tourists in early 2022.</p>' ||
                                                                                                                      '<p>While this might seem like great news for travelers planning their post-lockdown trips, in Myanmar, it''s complicated.</p>' ||
                                                                                                                      '<p>Most nations that closed their borders over the past two years did so solely to prevent the spread of Covid-19, but Myanmar is also still dealing with the aftereffects of a February 2021 coup in which a military junta overthrew the country''s democratically elected government.</p>' ||
                                                                                                                      '<p>Visiting Myanmar, which has previously spent decades under military rule, has always presented dilemmas for travelers weighing up whether their trip will support what has in the past been labeled an oppressive regime, or will help locals who need outside lifelines.</p>' ||
                                                                                                                      '<p>The question is now, with Covid still an issue across the region and the wider world of travel, plus the turmoil currently gripping the country, will anyone come?</p>' ||
                                                                                                                      '<p>Officials have already set up a website, anticipating tourist interest, but have made it clear that any opening will be subject to successful Covid mitigation being in place.</p>' ||
                                                                                                                      '<p>"We are planning to reopen tourism for vaccinated tourists if plans are well-prepared for safe and convenient travel," Zeyar Htun, deputy director of the Public Relations and Information Department at the military-run Ministry of Hotels & Tourism, confirmed to CNN Travel.</p>' ||
                                                                                                                      '<p>Meanwhile, some international travelers are being warned by their own governments to stay away, due to both Covid concerns and instability in the wake of the coup.</p>' ||
                                                                                                                      '<p>The US State Department currently has two level four "do not visit" alerts for Burma, as it refers to Myanmar, one for its high number of coronavirus cases, and one for the ongoing political situation.</p>' ||
                                                                                                                      '<p>In a separate advisory, it notes "Burma is facing a grave political, economic, human rights and humanitarian crisis due to a brutal crackdown by a powerful military that acts with impunity."</p>','travel');
insert into NEWS(title,body) values
                                    ( 'Israel Invests Billions in its Arab Population, Will BDS-ers Finally Admit Defeat?','<p>Last week, Israel announced one of the biggest ever investments in its Arab population. On October 24, Israel’s cabinet passed the first-ever bill of its kind pending final approval in Israel’s parliament, the Knesset, to allocate more than $11.5 billion to increase living standards among the country’s Arab population.</p>' ||
                                                                                                                            '<p>The funds will go towards improving the quality of life in various sectors, including education, employment, and housing. The Israeli government is also investing funds in increasing employment opportunities for the country’s Arab women. Additionally, more than 10 per cent of the funds are specifically allocated to combating high crime rates among Israel’s Arab population.</p>' ||
                                                                                                                           '<p>Currently, Israeli Arabs – despite enjoying identical civil and democratic rights as their Jewish neighbours –don’t often enjoy the same levels of socioeconomic wealth and comforts. And whereas this is primarily attributable to real challenges in Israel facing economic integration, anti-Israel activists have long eschewed any nuance, and claimed that the gap in living standards is now, and has always been, purposeful racism on Israel’s part.</p>' ||
                                                                                                                           '<p>After all, demonizing Israel with simplistic explanations is always easier than explaining the complex reality that Israeli Arabs enjoy full rights as Israeli citizens, but that doesn’t mean their living standards can’t be improved.</p>' ||
                                                                                                                           '<p>In fact, no less than Mansour Abbas, leader of the Arab-Islamist Ra’am party, spoke out praising the new Israeli government investments.</p>' ||
                                                                                                                           '<p>The investments “will go a long way to close the gaps between Jewish and Arab sectors,” Abbas said.</p>' ||
                                                                                                                           '<p>In June, Abbas made history when Ra’am became the first-ever Arab political party in Israel to sit in a governing coalition, holding the balance of power in Israel’s Knesset. While this was widely reported in the international news media, the significance of Abbas taking a seat in the Israeli government was a fatal blow to those voices who still attempt to argue that Israel practices widespread, systemic racism against its Arab population.</p>' ||
                                                                                                                           '<p>The facts notwithstanding, those voices bent on demonizing Israel and denying the Jewish People a right to their own historic homeland find a way to not only avoid ever giving credit to Israel, but they attempt to turn the tables and criticize Israel at every opportunity.</p>' ||
                                                                                                                           '<p>For example, Israel is the only country in the Middle East to offer protection under the law to its LGBTQ+ population, even hosting a pride parade in not just Tel Aviv, but even Jerusalem, the Jewish people’s 3,000 year-old historic capital. Meanwhile, next door in Hamas-ruled Gaza, homosexuals fear for their very lives. But to anti-Israel critics, Israel’s gay rights are little more than “pinkwashing,” whereby the Jewish State is allegedly merely trying to distract from its alleged poor treatment of the Palestinians.</p>' ||
                                                                                                                           '<p>Same too with Israel’s stellar environmental record. In the last 73 years, Israel has been creative in its stewardship of the environment, due in no small part to its own small size and lack of natural resources. From inventing drip irrigation, which waters plants and grass using a fraction of the water typically used, to planting millions of trees, to widespread collection of rain water for recycling, Israel is a world leader. But once again, BDS activists have responded with a simple rebuttal: greenwashing. The only reason, their argument goes, that Israel has an excellent environmental record is to once again hide its treatment of the Palestinians.</p>' ||
                                                                                                                           '<p>As absurd and illogical as the pinkwashing and greenwashing arguments are, due to their simplicity, they will unfortunately always find an audience seeking a simple rhetorical answer rather than the true, more complex one.</p>' ||
                                                                                                                           '<p>But Israel investing billions to improve the living standards of its own Arab population, which now numbers about 2.5 million, out of Israel’s total 9.3 million citizens? That will undoubtedly produce the same reaction from Israel’s die hard critics: they will likely disregard the investments, and the benefit which millions of Israeli Arabs will enjoy, and they will likely accuse Israel of, once again, terrible human rights abuses against Arabs.</p>' ||
                                                                                                                           '<p>However, as the arguments used by anti-Israel activists become more desperate and bizarre, bordering on self-parody, they will fortunately expose themselves as individuals and organizations not interested in improving the lives of Palestinians, but merely of demonizing Israel and attempting to harm the Jewish State in any way possible.</p>' ||
                                                                                                                           '<p>If only BDS supporters and activists would invest the same energy in building cooperation as in trying to destroy it, the lives of millions of Israeli Arabs and Palestinians would be immeasurably improved. But as long as they refuse to do that, it serves as a powerful demonstration of their true priorities.</p>' ),
                                    ('India Zika outbreak sees surge of nearly 100 cases','<p>At least 89 people, including 17 children, have tested positive for the Zika virus in a surge of cases in the Indian city of Kanpur, its health department said on Monday.</p>' ||
                                                                                          '<p>First discovered in 1947, the mosquito-borne virus Zika virus reached epidemic proportions in Brazil in 2015, when thousands of babies were born with microcephaly, a disorder that causes babies to be born with abnormally small heads and underdeveloped brains.</p>' ||
                                                                                          '<p>"There has been a surge in cases of the Zika virus and the health department has formed several teams to contain the spread," Dr Nepal Singh, chief medical officer of Kanpur district in India''s most populous state of Uttar Pradesh, told Reuters.</p>' ||
                                                                                          '<p>"There is one woman who is pregnant and we are paying special attention towards her."</p>' ||
                                                                                          '<p>Cases have been reported in several Indian states in recent years, though Amit Mohan Prasad, Uttar Pradesh''s top government bureaucrat for health and family welfare, told Reuters this was the first outbreak in the state.</p>' ||
                                                                                          '<p>The first Zika case in the industrial city of Kanpur was detected on October 23 and the number of cases has increased over the past week.</p>' ||
                                                                                          '<p>"People are testing positive because we are doing very aggressive contact tracing," said Prasad.</p>' ||
                                                                                          '<p>Authorities were increasing their surveillance of the outbreak and eliminating breeding grounds for the mosquitoes that transmit the virus, Singh said.</p>')
